# Generated by Django 5.0.6 on 2024-06-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('eligible_courses', models.CharField(max_length=200)),
                ('eligible_expense', models.CharField(max_length=200)),
                ('security', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='country')),
                ('short_description', models.TextField(default=None)),
                ('overview', models.TextField()),
                ('quick_facts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('textbooks', models.FileField(upload_to='textbooks/')),
                ('video_tutorial', models.FileField(upload_to='course_videos/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('test_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('passport_number', models.CharField(max_length=200)),
                ('contact_info', models.IntegerField()),
                ('nationality', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('visa_type', models.CharField(max_length=100)),
                ('passport_copy', models.FileField(upload_to='visa/passport')),
                ('financial_status', models.FileField(upload_to='visa/financial_status')),
                ('letter_of_acceptance', models.FileField(upload_to='visa/letter')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=200)),
                ('room_type', models.CharField(max_length=200)),
                ('facilities', models.TextField()),
                ('room_description', models.TextField()),
                ('rate', models.CharField(max_length=150)),
                ('nearby_attractions', models.CharField(max_length=200)),
                ('photos', models.ImageField(upload_to='accommodation/')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fees', models.TextField()),
                ('institute', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.institute')),
            ],
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('salary_range', models.CharField(max_length=200)),
                ('application_deadline', models.DateField()),
                ('contact_info', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('eligibility_criteria', models.CharField(max_length=200)),
                ('application_deadline', models.DateField()),
                ('award_amount', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('eligibility_criteria', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=200)),
                ('validity_period', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursematerial')),
                ('test_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testcenter')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='app.country')),
            ],
        ),
        migrations.AddField(
            model_name='institute',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='app.university'),
        ),
    ]
