# Generated by Django 5.0.6 on 2024-06-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
