# Generated by Django 5.0.6 on 2024-06-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_batch_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='titles',
            new_name='title',
        ),
    ]
