# Generated by Django 5.0.6 on 2024-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_titles_batch_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
