# Generated by Django 5.0.6 on 2024-06-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_batch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='image',
            field=models.ImageField(blank=True, upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
