# Generated by Django 5.0.6 on 2024-06-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_batch_image_alter_batch_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('candidate_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('mother_tongue', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expiry', models.DateField()),
                ('country_preferred', models.CharField(max_length=50)),
                ('study_plan', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('exam_type', models.CharField(max_length=10)),
                ('test_location', models.CharField(max_length=100)),
                ('test_date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('pte_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ielts_id', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_upload', models.FileField(upload_to='uploads/passports/')),
                ('address', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
