# Generated by Django 5.0.6 on 2024-06-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_examregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examregistration',
            name='passport_upload',
            field=models.FileField(upload_to='passports/'),
        ),
        migrations.CreateModel(
            name='BatchReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.batch')),
            ],
        ),
    ]
