# Generated by Django 5.0.6 on 2024-06-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_examregistration_passport_upload_batchreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankLoan',
        ),
    ]
