# Generated by Django 5.0.6 on 2024-06-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_bankloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('eligible_courses', models.CharField(max_length=200)),
                ('eligible_expense', models.CharField(max_length=200)),
                ('security', models.CharField(max_length=200)),
            ],
        ),
    ]
