# Generated by Django 5.0.6 on 2024-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bankloan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankloan',
            name='eligible_expense',
        ),
        migrations.RemoveField(
            model_name='bankloan',
            name='security',
        ),
        migrations.AddField(
            model_name='bankloan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='loan_term_years',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='loan_type',
            field=models.CharField(choices=[('secured', 'Secured'), ('unsecured', 'Unsecured')], default=None, max_length=50),
        ),
    ]
