# Generated by Django 5.0.6 on 2024-06-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_bankloan_eligible_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcenter',
            name='address',
        ),
        migrations.RemoveField(
            model_name='testcenter',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='testcenter',
            name='test_name',
        ),
        migrations.AddField(
            model_name='testcenter',
            name='contact_email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='testcenter',
            name='contact_phone',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='testcenter',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcenter',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='testcenter',
            name='operating_hours',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='testcenter',
            name='website',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='testcenter',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
