# Generated by Django 5.0.6 on 2024-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_testcenter_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcenter',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
