# Generated by Django 5.0.6 on 2024-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_testcenter_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
