# Generated by Django 5.0.6 on 2024-06-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
