# Generated by Django 5.0.6 on 2024-07-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_comment_date_alter_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
