# Generated by Django 5.0.6 on 2024-07-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_comment_date_alter_reply_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='type',
        ),
    ]
